version: '3'

services:
  app-db:
    image: postgres:14.5-alpine
    container_name: app-db
    environment:
      - POSTGRES_PASSWORD=${APP_PG_PASS:?database password not set}
      - PGUSER=${APP_PG_USER:?database user not set}
      - POSTGRES_DB=$APP_DB_NAME
    ports:
      - ${APP_PG_OUT_PORT}:${APP_PG_PORT}
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
  goph-keeper:
    build:
      context: .
      dockerfile: ./docker/goph_keeper
    container_name: goph_keeper
    volumes:
      - ./config:/root/config
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - app-db
    links:
      - app-db
      - redis
    command: sh -c "until nc -z app-db ${APP_PG_PORT}; do sleep 1; done && until nc -z redis_container 6379; do sleep 1; done && ./goph_keeper"
