version: '3'

services:
  app-db:
    image: postgres:14.5-alpine
    container_name: app-db
    environment:
      - POSTGRES_PASSWORD=${APP_PG_PASS:?database password not set}
      - PGUSER=${APP_PG_USER:?database user not set}
      - POSTGRES_DB=$APP_DB_NAME
    ports:
      - ${APP_PG_OUT_PORT}:${APP_PG_PORT}
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
