// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: grpc/goph_keeper/v1/goph_keeper.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GophKeeperV1Service_RegisterUser_FullMethodName       = "/grpc.goph_keeper.v1.GophKeeperV1Service/RegisterUser"
	GophKeeperV1Service_AuthenticateUser_FullMethodName   = "/grpc.goph_keeper.v1.GophKeeperV1Service/AuthenticateUser"
	GophKeeperV1Service_StorePrivateData_FullMethodName   = "/grpc.goph_keeper.v1.GophKeeperV1Service/StorePrivateData"
	GophKeeperV1Service_SyncData_FullMethodName           = "/grpc.goph_keeper.v1.GophKeeperV1Service/SyncData"
	GophKeeperV1Service_RequestPrivateData_FullMethodName = "/grpc.goph_keeper.v1.GophKeeperV1Service/RequestPrivateData"
)

// GophKeeperV1ServiceClient is the client API for GophKeeperV1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GophKeeperV1ServiceClient interface {
	// User registration
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	// User authentication
	AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error)
	// Storing private data (streaming)
	StorePrivateData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StorePrivateDataRequest, StorePrivateDataResponse], error)
	// Synchronizing data (streaming)
	SyncData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncDataRequest, SyncDataResponse], error)
	// Requesting private data (streaming)
	RequestPrivateData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestPrivateDataRequest, RequestPrivateDataResponse], error)
}

type gophKeeperV1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGophKeeperV1ServiceClient(cc grpc.ClientConnInterface) GophKeeperV1ServiceClient {
	return &gophKeeperV1ServiceClient{cc}
}

func (c *gophKeeperV1ServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, GophKeeperV1Service_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperV1ServiceClient) AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateUserResponse)
	err := c.cc.Invoke(ctx, GophKeeperV1Service_AuthenticateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperV1ServiceClient) StorePrivateData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StorePrivateDataRequest, StorePrivateDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GophKeeperV1Service_ServiceDesc.Streams[0], GophKeeperV1Service_StorePrivateData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StorePrivateDataRequest, StorePrivateDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeeperV1Service_StorePrivateDataClient = grpc.ClientStreamingClient[StorePrivateDataRequest, StorePrivateDataResponse]

func (c *gophKeeperV1ServiceClient) SyncData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncDataRequest, SyncDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GophKeeperV1Service_ServiceDesc.Streams[1], GophKeeperV1Service_SyncData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncDataRequest, SyncDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeeperV1Service_SyncDataClient = grpc.ClientStreamingClient[SyncDataRequest, SyncDataResponse]

func (c *gophKeeperV1ServiceClient) RequestPrivateData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestPrivateDataRequest, RequestPrivateDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GophKeeperV1Service_ServiceDesc.Streams[2], GophKeeperV1Service_RequestPrivateData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestPrivateDataRequest, RequestPrivateDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeeperV1Service_RequestPrivateDataClient = grpc.BidiStreamingClient[RequestPrivateDataRequest, RequestPrivateDataResponse]

// GophKeeperV1ServiceServer is the server API for GophKeeperV1Service service.
// All implementations must embed UnimplementedGophKeeperV1ServiceServer
// for forward compatibility.
type GophKeeperV1ServiceServer interface {
	// User registration
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	// User authentication
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error)
	// Storing private data (streaming)
	StorePrivateData(grpc.ClientStreamingServer[StorePrivateDataRequest, StorePrivateDataResponse]) error
	// Synchronizing data (streaming)
	SyncData(grpc.ClientStreamingServer[SyncDataRequest, SyncDataResponse]) error
	// Requesting private data (streaming)
	RequestPrivateData(grpc.BidiStreamingServer[RequestPrivateDataRequest, RequestPrivateDataResponse]) error
	mustEmbedUnimplementedGophKeeperV1ServiceServer()
}

// UnimplementedGophKeeperV1ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGophKeeperV1ServiceServer struct{}

func (UnimplementedGophKeeperV1ServiceServer) RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedGophKeeperV1ServiceServer) AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedGophKeeperV1ServiceServer) StorePrivateData(grpc.ClientStreamingServer[StorePrivateDataRequest, StorePrivateDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StorePrivateData not implemented")
}
func (UnimplementedGophKeeperV1ServiceServer) SyncData(grpc.ClientStreamingServer[SyncDataRequest, SyncDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SyncData not implemented")
}
func (UnimplementedGophKeeperV1ServiceServer) RequestPrivateData(grpc.BidiStreamingServer[RequestPrivateDataRequest, RequestPrivateDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RequestPrivateData not implemented")
}
func (UnimplementedGophKeeperV1ServiceServer) mustEmbedUnimplementedGophKeeperV1ServiceServer() {}
func (UnimplementedGophKeeperV1ServiceServer) testEmbeddedByValue()                             {}

// UnsafeGophKeeperV1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GophKeeperV1ServiceServer will
// result in compilation errors.
type UnsafeGophKeeperV1ServiceServer interface {
	mustEmbedUnimplementedGophKeeperV1ServiceServer()
}

func RegisterGophKeeperV1ServiceServer(s grpc.ServiceRegistrar, srv GophKeeperV1ServiceServer) {
	// If the following call pancis, it indicates UnimplementedGophKeeperV1ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GophKeeperV1Service_ServiceDesc, srv)
}

func _GophKeeperV1Service_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperV1ServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperV1Service_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperV1ServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperV1Service_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperV1ServiceServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperV1Service_AuthenticateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperV1ServiceServer).AuthenticateUser(ctx, req.(*AuthenticateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperV1Service_StorePrivateData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GophKeeperV1ServiceServer).StorePrivateData(&grpc.GenericServerStream[StorePrivateDataRequest, StorePrivateDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeeperV1Service_StorePrivateDataServer = grpc.ClientStreamingServer[StorePrivateDataRequest, StorePrivateDataResponse]

func _GophKeeperV1Service_SyncData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GophKeeperV1ServiceServer).SyncData(&grpc.GenericServerStream[SyncDataRequest, SyncDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeeperV1Service_SyncDataServer = grpc.ClientStreamingServer[SyncDataRequest, SyncDataResponse]

func _GophKeeperV1Service_RequestPrivateData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GophKeeperV1ServiceServer).RequestPrivateData(&grpc.GenericServerStream[RequestPrivateDataRequest, RequestPrivateDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeeperV1Service_RequestPrivateDataServer = grpc.BidiStreamingServer[RequestPrivateDataRequest, RequestPrivateDataResponse]

// GophKeeperV1Service_ServiceDesc is the grpc.ServiceDesc for GophKeeperV1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GophKeeperV1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.goph_keeper.v1.GophKeeperV1Service",
	HandlerType: (*GophKeeperV1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _GophKeeperV1Service_RegisterUser_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _GophKeeperV1Service_AuthenticateUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StorePrivateData",
			Handler:       _GophKeeperV1Service_StorePrivateData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncData",
			Handler:       _GophKeeperV1Service_SyncData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RequestPrivateData",
			Handler:       _GophKeeperV1Service_RequestPrivateData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/goph_keeper/v1/goph_keeper.proto",
}
