name: Build Windows

on: [workflow_call]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Build server for Windows
        run: |
          mkdir -p build/windows
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -o build/windows/server.exe ./cmd/server
        shell: pwsh

      - name: Create server config file
        run: |
          echo "server:
            host: localhost
            port: 8080
          redis:
            host: localhost
            port: 6379
            password: \"my_redis_password\"
          db:
            dsn: \"postgres://postgres:root@localhost:5432\"" > build/windows/config-server.yaml

      - name: Build client for Windows
        run: |
          mkdir -p build/windows
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -o build/windows/client.exe ./cmd/client
        shell: pwsh

      - name: Create client config file
        run: |
          echo "server:
            host: localhost
            port: 8080" > build/windows/config-client.yaml

      - name: Create release directory
        run: mkdir -p release

      - name: Create ZIP archive for Windows
        run: |
          cd build
          Compress-Archive -Path .\windows -DestinationPath ..\release\windows.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows
          path: release/windows.zip

      - name: Check build-windows success
        if: failure()
        run: echo "Build for Windows failed"
